<?php

include 'conexion.php';

$DNI=$_POST['DNI'];
$FECHA_REGISTRO=$_POST['FECHA_REGISTRO'];
$COORDENADAS=$_POST['COORDENADAS'];
$TIPO_DE_VIVIENDA=$_POST['TIPO_DE_VIVIENDA'];
$DUEÑO_DE_LA_VIVIENDA=$_POST['DUEÑO_DE_LA_VIVIENDA'];
$CANTIDAD_DE_PIEZAS=$_POST['CANTIDAD_DE_PIEZAS'];
$LUGAR_PARA_COCINAR=$_POST['LUGAR_PARA_COCINAR'];
$USA_PARA_COCINAR=$_POST['USA_PARA_COCINAR'];
$MATERIAL_PREDOMINANTE_EN_LAS_PAREDES_EXTERIORES=$_POST['MATERIAL_PREDOMINANTE_EN_LAS_PAREDES_EXTERIORES'];
$REVESTIMIENTO_EXTERNO_O_REVOQUE=$_POST['REVESTIMIENTO_EXTERNO_O_REVOQUE'];
$MATERIAL_DE_LOS_PISOS=$_POST['MATERIAL_DE_LOS_PISOS'];
$CIELORRASOS=$_POST['CIELORRASOS'];
$MATERIAL_EXTERIOR_DEL_TECHO=$_POST['MATERIAL_EXTERIOR_DEL_TECHO'];
$AGUA=$_POST['AGUA'];
$ORIGEN_AGUA=$_POST['ORIGEN_AGUA'];
$EXCRETAS=$_POST['EXCRETAS'];
$ELECTRICIDAD=$_POST['ELECTRICIDAD'];
$GAS=$_POST['GAS'];
$ALMACENA_AGUA_DE_LLUVIA=$_POST['ALMACENA_AGUA_DE_LLUVIA'];
$ARBOLES=$_POST['ARBOLES'];
$BAÑO=$_POST['BAÑO'];
$EL_BAÑO_TIENE=$_POST['EL_BAÑO_TIENE'];
$NIEVE_HIELO=$_POST['NIEVE_HIELO'];
$PERROS_SUELTOS=$_POST['PERROS_SUELTOS'];

$consulta="insert into entre_rios values('".$DNI."', '".$FECHA_REGISTRO."','".$COORDENADAS."', '".$TIPO_DE_VIVIENDA."',
											'".$DUEÑO_DE_LA_VIVIENDA."', '".$CANTIDAD_DE_PIEZAS."','".$LUGAR_PARA_COCINAR."', 
											'".$USA_PARA_COCINAR."','".$MATERIAL_PREDOMINANTE_EN_LAS_PAREDES_EXTERIORES."', 
											'".$REVESTIMIENTO_EXTERNO_O_REVOQUE."','".$MATERIAL_DE_LOS_PISOS."', '".$CIELORRASOS."',
											'".$MATERIAL_EXTERIOR_DEL_TECHO."', '".$AGUA."','".$ORIGEN_AGUA."', '".$EXCRETAS."',
											'".$ELECTRICIDAD."', '".$GAS."','".$ALMACENA_AGUA_DE_LLUVIA."', '".$ARBOLES."',
											'".$BAÑO."', '".$EL_BAÑO_TIENE."','".$NIEVE_HIELO."', '".$PERROS_SUELTOS."')";

mysqli_query($conexion, $consulta) or die ("Problemas al insertar".mysqli_error($conexion));
mysqli_close($conexion);

?>
