<?php

include 'conexion.php';

$COORDENADAS=$_POST['COORDENADAS'];
$FACTORES_DE_RIESGO=$_POST['FACTORES_DE_RIESGO'];
$EFECTOR=$_POST['EFECTOR'];
$OBSERVACIONES=$_POST['OBSERVACIONES'];
$EDUCACION=$_POST['EDUCACION'];
$VITAMINA_D=$_POST['VITAMINA_D'];
$ULTIMO_CONTROL=$_POST['ULTIMO_CONTROL'];
$ENFERMEDAD_ASOCIADA_EMBARAZO=$_POST['ENFERMEDAD_ASOCIADA_EMBARAZO'];
$CERTIFICADO_DISCAPACIDAD=$_POST['CERTIFICADO_DISCAPACIDAD'];
$TIPO_DE_DISCAPACIDAD=$_POST['TIPO_DE_DISCAPACIDAD'];
$ACOMPAÑAMIENTO=$_POST['ACOMPAÑAMIENTO'];
$TRASTORNOS_EN_NIÑOS=$_POST['TRASTORNOS_EN_NIÑOS'];
$ADICCIONES=$_POST['ADICCIONES'];
$ACTIVIDADES_DE_OCIO=$_POST['ACTIVIDADES_DE_OCIO'];
$OCIO_DONDE=$_POST['OCIO_DONDE'];
$TIPO_DE_VIOLENCIA=$_POST['TIPO_DE_VIOLENCIA'];
$MODALIDAD_VIOLENCIA=$_POST['MODALIDAD_VIOLENCIA'];
$TRASTORNOS_MENTALES=$_POST['TRASTORNOS_MENTALES'];
$ENFERMEDADES_CRONICAS=$_POST['ENFERMEDADES_CRONICAS'];
$PLAN_SOCIAL=$_POST['PLAN_SOCIAL'];

$consulta="insert into datos_persona values('".$COORDENADAS."', '".$FACTORES_DE_RIESGO."','".$EFECTOR."', '".$OBSERVACIONES."',
											'".$EDUCACION."', '".$VITAMINA_D."','".$ULTIMO_CONTROL."', 
											'".$ENFERMEDAD_ASOCIADA_EMBARAZO."','".$CERTIFICADO_DISCAPACIDAD."', 
											'".$TIPO_DE_DISCAPACIDAD."','".$ACOMPAÑAMIENTO."', '".$TRASTORNOS_EN_NIÑOS."',
											'".$ADICCIONES."', '".$ACTIVIDADES_DE_OCIO."','".$OCIO_DONDE."', '".$TIPO_DE_VIOLENCIA."',
											'".$MODALIDAD_VIOLENCIA."', '".$TRASTORNOS_MENTALES."','".$ENFERMEDADES_CRONICAS."', 
											'".$PLAN_SOCIAL."')";

mysqli_query($conexion, $consulta) or die ("Problemas al insertar".mysqli_error($conexion));
mysqli_close($conexion);

?>
